version: '3'

services:
  setup:
    build: .
    depends_on:
      - mysql
    environment:
      - RAILS_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE=rails_mysql_kubernetes_development
      - MYSQL_PORT=3306
      - MYSQL_HOST=db
    command: "bin/rails db:migrate"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=rails_mysql_kubernetes_development
  web:
    build: .
    command: "bin/bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
      - setup
    environment:
      - RAILS_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE=rails_mysql_kubernetes_development
      - MYSQL_PORT=3306
      - MYSQL_HOST=db
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: "bin/bundle exec sidekiq -C config/sidekiq.yml"
