apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: rails-mysql-kubernetes
spec:
  ports:
    - port: 3306
  selector:
    app: rails-mysql-kubernetes
    tier: database
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    app: rails-mysql-kubernetes
spec:
  replicas: 1
  selector:
    app: rails-mysql-kubernetes
    tier: database
  template:
    metadata:
      name: mysql
      labels:
        app: rails-mysql-kubernetes
        tier: database
    spec:
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-persistent-volume-claim
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-root-password
              key: password
        - name: MYSQL_DATABASE
          value: rails_mysql_kubernetes_development
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-persistent-volume

