apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: rails_mysql_kubernetes
spec:
  ports:
    - port: 6379
  selector:
    app: rails_mysql_kubernetes
    tier: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: rails_mysql_kubernetes
    tier: redis
  template:
    metadata:
      name: redis
      labels:
        app: rails_mysql_kubernetes
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2-alpine
        ports:
        - containerPort: 6379
