apiVersion: v1
kind: ReplicationController
metadata:
  name: sidekiq
spec:
  replicas: 1
  selector:
    app: rails_mysql_kubernetes
    tier: sidekiq
  template:
    metadata:
      name: sidekiq
      labels:
        app: rails_mysql_kubernetes
        tier: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: namtx/rails_mysql_kubernetes:latest
        args: ["sidekiq -C config/sidekiq.yml"]
        env:
        - name: RAILS_ENV
          value: production
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "db-root-password"
              key: "password"
        - name: REDIS_URL
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
